version: '3.8'

services:
  forecast-service:
    build:
      context: ./forecast-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_NAME=forecastdb
      - SSL_MODE=disable
      - JWT_SECRET=your_jwt_secret

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: forecastdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
