// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func InitializeService() *MyService {
	repository := NewRepository()
	myService := NewMyService(repository)
	return myService
}
