// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"forecast-service/service"
	"forecast-service/service/config"
)

// Injectors from wire.go:

func InitializeService() service.ForecastService {
	configConfig := config.LoadConfig()
	citiesHandler := service.NewCitiesHandler(configConfig)
	forecastsHandler := service.NewForecastsHandler()
	forecastService := service.NewForecastService(configConfig, citiesHandler, forecastsHandler)
	return forecastService
}
