// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"forecast-service/service"
	"forecast-service/service/config"
	"forecast-service/service/repository"
	"forecast-service/service/repository/middleware"
)

// Injectors from wire.go:

func InitializeService() service.ForecastService {
	configConfig := config.LoadConfig()
	db := repository.NewGormDB(configConfig)
	cityRepository := repository.NewCityRepository(db)
	userRepository := repository.NewUserRepository(db)
	forecastRepository := repository.NewForecastRepository(db)
	citiesHandler := service.NewCitiesHandler(cityRepository, userRepository, forecastRepository)
	forecastsHandler := service.NewForecastsHandler(forecastRepository, userRepository)
	middlewareMiddleware := middleware.NewMiddleware(configConfig, userRepository)
	forecastService := service.NewForecastService(configConfig, citiesHandler, forecastsHandler, middlewareMiddleware)
	return forecastService
}
