openapi: 3.0.0
info:
  title: Forecast Service
  description: "API for managing cities, forecasts, and user favourites in a forecast\
    \ service."
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/kiIIer/ForecastService/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://api.forecastservice.com/v1
paths:
  /cities:
    get:
      summary: Search city by name
      parameters:
      - name: name
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: A list of cities
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/City'
                x-content-type: application/json
    post:
      summary: Create a new city
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/cities_body'
        required: true
      responses:
        "201":
          description: City created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/City'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
      security:
      - bearerAuth: []
  /cities/{id}:
    get:
      summary: Get city by ID
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: City found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/City'
        "404":
          description: City not found
    delete:
      summary: Delete city by ID
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "204":
          description: City deleted
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: City not found
      security:
      - bearerAuth: []
  /cities/{id}/forecasts:
    get:
      summary: Get forecasts for city by ID
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: A list of forecasts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Forecast'
                x-content-type: application/json
        "404":
          description: City not found
  /forecasts:
    get:
      summary: Get all forecasts
      responses:
        "200":
          description: A list of forecasts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Forecast'
                x-content-type: application/json
    post:
      summary: Create a new forecast
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Forecast'
        required: true
      responses:
        "201":
          description: Forecast created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Forecast'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
      security:
      - bearerAuth: []
  /forecasts/{id}:
    get:
      summary: Get forecast by ID
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: Forecast found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Forecast'
        "404":
          description: Forecast not found
    delete:
      summary: Delete forecast by ID
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "204":
          description: Forecast deleted
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Forecast not found
      security:
      - bearerAuth: []
  /favourites:
    get:
      summary: Get user favourites
      responses:
        "200":
          description: A list of user favourites
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/City'
                x-content-type: application/json
        "401":
          description: Unauthorized
      security:
      - bearerAuth: []
    post:
      summary: Add city to user favourites
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/favourites_body'
        required: true
      responses:
        "201":
          description: City added to user favourites
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/City'
        "401":
          description: Unauthorized
      security:
      - bearerAuth: []
  /favourites/{id}:
    delete:
      summary: Remove city from user favourites
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "204":
          description: City removed from user favourites
        "401":
          description: Unauthorized
        "404":
          description: City not found in user favourites
      security:
      - bearerAuth: []
  /upcoming-forecasts:
    get:
      summary: Get upcoming forecasts for user favourites
      responses:
        "200":
          description: A list of forecasts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Forecast'
                x-content-type: application/json
        "401":
          description: Unauthorized
      security:
      - bearerAuth: []
components:
  schemas:
    City:
      type: object
      properties:
        city_id:
          type: integer
        name:
          type: string
      example:
        name: name
        city_id: 0
    Forecast:
      type: object
      properties:
        forecast_id:
          type: integer
        city_id:
          type: integer
        date_of_forecast:
          type: string
          format: date
        chance_of_rain:
          type: number
          format: float
        temperature:
          type: number
          format: float
      example:
        temperature: 5.962134
        date_of_forecast: 2000-01-23
        chance_of_rain: 1.4658129
        forecast_id: 0
        city_id: 6
    cities_body:
      type: object
      properties:
        name:
          type: string
    favourites_body:
      type: object
      properties:
        city_id:
          type: integer
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
