@startuml
participant Admin as A
participant "Site" as S
participant Server as SV
participant Database as DB

A -> S: Входить у свій аккаунт
A -> S: Вводить назву населеного пункту і натискає "Додати прогноз"
A <- S: Відображення вікна для додавання прогнозу
A -> S: Вводить прогноз і натискає "Зберегти"
S -> SV: Валідація даних
SV -> DB: Запит на додавання даних
SV <- DB: Відповідь з доданими даними
S <- SV: Передає відповідь сервера
A <- S: Відображення відповіді сервера
@enduml