@startuml
actor User as U
participant Website as W
participant Server as S
database Database as DB

U -> W: Введення ім'я міста
W -> S: Запит на отримання списку схожих міст
S -> DB: Запит до бази даних
DB --> S: Дані з бази даних
S --> W: Список схожих міст
W -> U: Показ списку міст
U -> W: Вибір міста
W -> S: Запит на отримання прогнозу
S -> DB: Запит до бази даних
DB --> S: Дані з бази даних для прогнозу
S --> W: Прогноз для вибраного міста
W -> U: Показ прогнозу
@enduml